apiVersion: batch/v1
kind: Job
metadata:
  name: fcvm-kubectl-example
  namespace: fcvm
spec:
  ttlSecondsAfterFinished: 10
  backoffLimit: 0
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
        # cluster-autoscaler.kubernetes.io/safe-to-evict: 'false'
      labels:
        app: fcvm
        env: miniconda
        project: azimuth
    spec:
      restartPolicy: Never
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: job-name
                operator: In
                values:
                - job-fcvm-kubectl-example
            topologyKey: "kubernetes.io/hostname"
      volumes:
        - name: fcvm-data-volume
          persistentVolumeClaim:
            claimName: fcvm-data-volume
      containers:
        - name: pytorch-job
          image: harbor.csis.astrazeneca.net/azimuth-iron/cai-bp/cuda121/codeserver
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /home/jovyan/fcvm-data-volume
              name: fcvm-data-volume
          env:
            - name: HTTP_PROXY
              value: http://azpzen.astrazeneca.net:9480
            - name: HTTPS_PROXY
              value: http://azpzen.astrazeneca.net:9480
            - name: NO_PROXY
              value: 10.0.0.0/8,172.29.0.0/8,astrazeneca.net
            # - name: WANDB_BASE_URL
            #   value: https://azimuth-wandb.paas-iron.astrazeneca.net
            # - name: WANDB_API_KEY
            #   valueFrom:
            #     secretKeyRef:
            #       key: KEY
            #       name: wandb
          command: [/usr/bin/bash, -c]
          args:
            - |
              export PATH="$HOME/bin:$PATH"
              export PATH="/home/jovyan/fcvm-data-volume/kzzr229/miniconda3/bin:$PATH"
              source ~/.bashrc
              source activate mcpl
              echo "-----nvidia check"
              nvidia-smi
              echo "-----training job" 
              cd /home/jovyan/fcvm-data-volume/kzzr229/workspace/MCPL-diffuser
              accelerate launch causalnet.py  --output_name "mcplall_init_controlnet" \
                --output_dir "./logs/logs_skin_cancer_data100" \
                --pretrained_model_name_or_path "/home/jovyan/fcvm-data-volume/kzzr229/workspace/MCPL-diffuser/.cache/huggingface/hub/models--lambdalabs--miniSD-diffusers/snapshots/26ed8a9bfbf76f46a6cf60517dde321f900c44ce" \
                --dataset 'skin_cancer' \
                --train_data_dir "/home/jovyan/fcvm-data-volume/kzzr229/workspace/causal_datasets/skin_cancer/sampling_100" \
                --learnable_property "object" \
                --resolution 256 \
                --train_batch_size 8 \
                --dataloader_num_workers 0 \
                --gradient_accumulation_steps 1 \
                --max_train_steps 15000 \
                --checkpointing_steps 999999 \
                --learning_rate 5e-6 \
                --lr_scheduler "constant" \
                --lr_warmup_steps 0 \
                --num_validation_images 1 \
                --placeholder_string 'a detailed skin cancer image of a age year old gender patient diagnosed with specific disease' \
                --presudo_words 'a,detailed,chest,skin,cancer,image,of,age,year,old,gender,patient,diagnosed,with,specific,disease' \
                --mcpl_training "False" \
                --mcpl_embedding_path "/home/jovyan/fcvm-data-volume/kzzr229/workspace/MCPL-diffuser/logs/logs_skin_cancer_data100/2024-12-05T23-21-52-mcpl-all/learned_embeds-steps-6000.safetensors" \
          resources:
            requests:
              memory: "100Gi"
              cpu: "10"
              # nvidia.com/gpu: "1"
            limits:
              memory: "100Gi"
              cpu: "10"
              # nvidia.com/gpu: "1"
      nodeSelector:
        instance-type: g5.8xlarge
      tolerations:
      - key: "as_gpu_g5_8xlarge_ns"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      - key: "as_gpu_g5_8xlarge_ne"
        operator: "Equal"
        value: "true"
        effect: "NoExecute"