apiVersion: batch/v1
kind: Job
metadata:
  name: kzzr229-celebahq-p2p3
  namespace: fcvm
spec:
  ttlSecondsAfterFinished: 10
  backoffLimit: 0
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
        # cluster-autoscaler.kubernetes.io/safe-to-evict: 'false'
      labels:
        app: fcvm
        env: miniconda
        project: azimuth
    spec:
      restartPolicy: Never
      hostIPC: true
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: job-name
                operator: In
                values:
                - job-fcvm-kubectl-example
            topologyKey: "kubernetes.io/hostname"
      volumes:
        - name: fcvm-data-volume
          persistentVolumeClaim:
            claimName: fcvm-data-volume
      containers:
        - name: pytorch-job
          image: harbor.csis.astrazeneca.net/azimuth-iron/cai-bp/cuda122/p4d:latest
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /home/jovyan/fcvm-data-volume
              name: fcvm-data-volume
          env:
            - name: HTTP_PROXY
              value: http://azpse.astrazeneca.net:9480
            - name: HTTPS_PROXY
              value: http://azpse.astrazeneca.net:9480
            - name: NO_PROXY
              value: 10.0.0.0/8,172.29.0.0/8,astrazeneca.net
            # - name: TMPDIR
            #   value: "/home/jovyan/vol-1/root_chen/git_chen/data/data_chen/tmp"
            # - name: WANDB_BASE_URL
            #   value: https://azimuth-wandb.paas-iron.astrazeneca.net
            # - name: WANDB_API_KEY
            #   valueFrom:
            #     secretKeyRef:
            #       key: KEY
            #       name: wandb
          command: [/usr/bin/bash, -c]
          args:
            - |
              export PATH="$HOME/bin:$PATH"
              export PATH="/home/jovyan/fcvm-data-volume/kzzr229/miniconda3/bin:$PATH"
              source ~/.bashrc
              source activate mcpl
              echo "-----nvidia check"
              nvidia-smi
              echo "-----training job" 
              cd /counterfactual_benchmark/methods/deepscm
              accelerate launch evaluate_SD_DSCM.py --editing p2p --anti-classifier --dataset "celebahq_simple" \
                --metrics "effectiveness" \
                --embeddings "lpips" \
                --bs 10 \
                --guidance_scale 1.5 \
                --num_steps 100 \
                --NTI "True" \
                --controlnet_path "/logs/logs_celebahq_simple_all/2025-10-07T14-56-05-controlnet_textcond_constrastive_7attrsgeneration_text_global_after/controlnet-steps-200000.safetensors" \
                --mcpl_embedding_path "/logs/logs_celebahq_simple_all/2025-10-07T14-56-05-controlnet_textcond_constrastive_7attrsgeneration_text_global_after/learned_embeds-steps-200000.safetensors"

          resources:
            requests:
              memory: "200Gi"
              cpu: "20"
              nvidia.com/gpu: 4
            limits:
              memory: "200Gi"
              cpu: "20"
              nvidia.com/gpu: 4
      nodeSelector:
        #kubernetes.io/hostname: ip-10-201-11-210.emea.astrazeneca.net
        instance-type: p4d.24xlarge
      tolerations:
      - key: "as_gpu_p4d_24xlarge_reserved_ns"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      - key: "as_gpu_p4d_24xlarge_reserved_ne"
        operator: "Equal"
        value: "true"
        effect: "NoExecute"